package com.goodwy.audiobook.uitools

import com.goodwy.audiobook.R
import kotlinx.serialization.json.Json.Default.context

val white: Int = android.graphics.Color.parseColor("#FFFFFFFF")
val backgroundLight: Int = android.graphics.Color.parseColor("#FFfafafa")
val grey: Int = android.graphics.Color.parseColor("#FFE0E0E0")
val grey2: Int = android.graphics.Color.parseColor("#c6c6c7")
val dark2: Int = android.graphics.Color.parseColor("#394248")
val dark: Int = android.graphics.Color.parseColor("#FF272f35")
val backgroundDark: Int = android.graphics.Color.parseColor("#1e2225")
val black: Int = android.graphics.Color.parseColor("#FF000000")

//ios
val ios_red_b : Int = android.graphics.Color.parseColor("#ff453a")
val ios_red_w : Int = android.graphics.Color.parseColor("#ff3b30")
val ios_orange_b : Int = android.graphics.Color.parseColor("#ff9f0a")
val ios_orange_w : Int = android.graphics.Color.parseColor("#ff9500")
val ios_yellow_b : Int = android.graphics.Color.parseColor("#ffd60a")
val ios_yellow_w : Int = android.graphics.Color.parseColor("#ffcc00")
val ios_green_b : Int = android.graphics.Color.parseColor("#32d74b")
val ios_green_w : Int = android.graphics.Color.parseColor("#34c759")
val ios_teal_b : Int = android.graphics.Color.parseColor("#64d2ff")
val ios_teal_w : Int = android.graphics.Color.parseColor("#5ac8fa")
val ios_blue_b : Int = android.graphics.Color.parseColor("#0a84ff")
val ios_blue_w : Int = android.graphics.Color.parseColor("#007aff")
val ios_indigo_b : Int = android.graphics.Color.parseColor("#5e5ce6")
val ios_indigo_w : Int = android.graphics.Color.parseColor("#5856d6")
val ios_purple_b : Int = android.graphics.Color.parseColor("#bf5af2")
val ios_purple_w : Int = android.graphics.Color.parseColor("#af52de")
val ios_pink_b : Int = android.graphics.Color.parseColor("#ff375f")
val ios_pink_w : Int = android.graphics.Color.parseColor("#ff2d55")

//material
val md_red_500 : Int = android.graphics.Color.parseColor("#f44336")
val md_pink_500 : Int = android.graphics.Color.parseColor("#e91e63")
val md_purple_500 : Int = android.graphics.Color.parseColor("#9c27b0")
val md_deep_purple_500 : Int = android.graphics.Color.parseColor("#673ab7")
val md_indigo_500 : Int = android.graphics.Color.parseColor("#3f51b5")
val md_blue_500 : Int = android.graphics.Color.parseColor("#2196f3")
val md_light_blue_500 : Int = android.graphics.Color.parseColor("#03a9f4")
val md_cyan_500 : Int = android.graphics.Color.parseColor("#00bcd4")
val md_teal_500 : Int = android.graphics.Color.parseColor("#009688")
val md_green_500 : Int = android.graphics.Color.parseColor("#4caf50")
val md_light_green_500 : Int = android.graphics.Color.parseColor("#8bc34a")
val md_lime_500 : Int = android.graphics.Color.parseColor("#cddc39")
val md_yellow_500 : Int = android.graphics.Color.parseColor("#ffeb3b")
val md_amber_500 : Int = android.graphics.Color.parseColor("#ffc107")
val md_orange_500 : Int = android.graphics.Color.parseColor("#ff9800")
val md_deep_orange_500 : Int = android.graphics.Color.parseColor("#ff5722")
val md_brown_500 : Int = android.graphics.Color.parseColor("#795548")
val md_grey_500 : Int = android.graphics.Color.parseColor("#9e9e9e")
val md_blue_grey_500 : Int = android.graphics.Color.parseColor("#607d8b")

val md_red_700 : Int = android.graphics.Color.parseColor("#D32F2F")
val md_pink_700 : Int = android.graphics.Color.parseColor("#C2185B")
val md_purple_700 : Int = android.graphics.Color.parseColor("#7B1FA2")
val md_deep_purple_700 : Int = android.graphics.Color.parseColor("#512DA8")
val md_indigo_700 : Int = android.graphics.Color.parseColor("#303F9F")
val md_blue_700 : Int = android.graphics.Color.parseColor("#1976D2")
val md_light_blue_700 : Int = android.graphics.Color.parseColor("#0288D1")
val md_cyan_700 : Int = android.graphics.Color.parseColor("#0097A7")
val md_teal_700 : Int = android.graphics.Color.parseColor("#00796B")
val md_green_700 : Int = android.graphics.Color.parseColor("#388E3C")
val md_light_green_700 : Int = android.graphics.Color.parseColor("#689F38")
val md_lime_700 : Int = android.graphics.Color.parseColor("#AFB42B")
val md_yellow_700 : Int = android.graphics.Color.parseColor("#FBC02D")
val md_amber_700 : Int = android.graphics.Color.parseColor("#FFA000")
val md_orange_700 : Int = android.graphics.Color.parseColor("#F57C00")
val md_deep_orange_700 : Int = android.graphics.Color.parseColor("#E64A19")
val md_brown_700 : Int = android.graphics.Color.parseColor("#5D4037")
val md_grey_700 : Int = android.graphics.Color.parseColor("#616161")
val md_blue_grey_700 : Int = android.graphics.Color.parseColor("#455A64")

//original
val Vintage2: Int = android.graphics.Color.parseColor("#FF8C2D2D")
val Meetup: Int = android.graphics.Color.parseColor("#FFED1744")
val Oblivion: Int = android.graphics.Color.parseColor("#FFD25252")
val Waaark: Int = android.graphics.Color.parseColor("#FFF76C6C")
val Vibrant: Int = android.graphics.Color.parseColor("#FFEC691E")
val Amazon: Int = android.graphics.Color.parseColor("#FFFF9900")
val Bing: Int = android.graphics.Color.parseColor("#FFFFB900")
val Flax2: Int = android.graphics.Color.parseColor("#FFECBC1B")
val Desert2: Int = android.graphics.Color.parseColor("#FF90A04A")
val Tasty: Int = android.graphics.Color.parseColor("#FF437356")
val Rio: Int = android.graphics.Color.parseColor("#FF0B4239")
val Weber: Int = android.graphics.Color.parseColor("#FF729F98")
val Periscope: Int = android.graphics.Color.parseColor("#FF40A4C4")
val Obsidian: Int = android.graphics.Color.parseColor("#FF678CB1")
val blue: Int = android.graphics.Color.parseColor("#FF4C86CB")
val Vitamin: Int = android.graphics.Color.parseColor("#FF0359AE")
val Philips: Int = android.graphics.Color.parseColor("#FF2F435E")
val Inkpot: Int = android.graphics.Color.parseColor("#FF6068B2")
val Twitch: Int = android.graphics.Color.parseColor("#FF7E57C2")
val Fresh2: Int = android.graphics.Color.parseColor("#FF8A36BB")

//statusbar
val Vintage2Dark: Int = android.graphics.Color.parseColor("#FF772626")
val MeetupDark: Int = android.graphics.Color.parseColor("#FFC91339")
val OblivionDark: Int = android.graphics.Color.parseColor("#FFB24545")
val WaaarkDark: Int = android.graphics.Color.parseColor("#FFD15B5B")
val VibrantDark: Int = android.graphics.Color.parseColor("#FFC85919")
val AmazonDark: Int = android.graphics.Color.parseColor("#FFD88200")
val BingDark: Int = android.graphics.Color.parseColor("#FFD89D00")
val Flax2Dark: Int = android.graphics.Color.parseColor("#FFC89F16")
val Desert2Dark: Int = android.graphics.Color.parseColor("#FF7A883E")
val TastyDark: Int = android.graphics.Color.parseColor("#FF386149")
val RioDark: Int = android.graphics.Color.parseColor("#FF093830")
val WeberDark: Int = android.graphics.Color.parseColor("#FF608781")
val PeriscopeDark: Int = android.graphics.Color.parseColor("#FF368BA6")
val ObsidianDark: Int = android.graphics.Color.parseColor("#FF577796")
val blueDark: Int = android.graphics.Color.parseColor("#FF4D6CA2")
val VitaminDark: Int = android.graphics.Color.parseColor("#FF024B93")
val PhilipsDark: Int = android.graphics.Color.parseColor("#FF27384F")
val InkpotDark: Int = android.graphics.Color.parseColor("#FF515897")
val TwitchDark: Int = android.graphics.Color.parseColor("#FF6B49A4")
val Fresh2Dark: Int = android.graphics.Color.parseColor("#FF752D9E")
