package voice.common.constants

//THEME
const val THEME_LIGHT = 0
const val THEME_DARK = 1
const val THEME_AUTO = 2

//SKIP_BUTTON_STYLE
const val SKIP_BUTTON_CLASSIC = 0
const val SKIP_BUTTON_ROUND = 1

//PLAY_BUTTON_STYLE
const val PLAY_BUTTON_CLASSIC = 0
const val PLAY_BUTTON_ROUND = 1
const val PLAY_BUTTON_SQUARE = 2
const val PLAY_BUTTON_ROUND_AND_SQUARE = 3

//MINI_PLAYER_STYLE
const val MINI_PLAYER_PLAYER = 0
const val MINI_PLAYER_ROUND_BUTTON = 1
const val MINI_PLAYER_SQUARE_BUTTON = 2
const val MINI_PLAYER_ROUND_AND_SQUARE = 3

//PLAYER_BACKGROUND
const val PLAYER_BACKGROUND_THEME = 0
const val PLAYER_BACKGROUND_BLUR_COVER = 1
const val PLAYER_BACKGROUND_BLUR_COVER_2 = 2

//REPEAT_MODE
const val REPEAT_OFF = 0
const val REPEAT_ONE = 1
const val REPEAT_ALL = 2

//SORTING
const val SORTING_CLASSIC = 0
const val SORTING_NAME = 1
const val SORTING_LAST = 2
const val SORTING_AUTHOR = 3

//SORTING_BOOKMARK
const val SORTING_BOOKMARK_LAST = 0
const val SORTING_BOOKMARK_TIME = 1
const val SORTING_BOOKMARK_NAME = 2
