package com.goodwy.audiobooklite.common.pref

object PrefKeys {

  const val RESUME_ON_REPLUG = "RESUME_ON_REPLUG"
  const val AUTO_REWIND_AMOUNT = "AUTO_REWIND"
  const val SEEK_TIME = "SEEK_TIME"
  const val SEEK_TIME_REWIND = "SEEK_TIME_REWIND"
  const val COVER_RADIUS = "COVER_RADIUS"
  const val COVER_ELEVATION = "COVER_ELEVATION"
  const val SHAKE_TO_RESET = "SHAKE_TO_RESET"
  const val SLEEP_TIME = "SLEEP_TIME"
  const val SLEEP_TIMER_CURRENT_CHAPTER = "SLEEP_TIMER_CURRENT_CHAPTER"
  const val SINGLE_BOOK_FOLDERS = "singleBookFolders"
  const val COLLECTION_BOOK_FOLDERS = "folders"
  const val LIBRARY_BOOK_FOLDERS = "libraryBookFolders"
  const val CURRENT_BOOK = "currentBook2"
  const val DARK_THEME = "darkTheme"
  const val GRID_MODE = "gridView"
  const val CONTENTS_BUTTON_MODE = "tintNavBar"
  const val SHOW_RATING = "showRatingPref"
  const val SHOW_SLIDER_VOLUME = "showSliderVolumePref"
  const val DEV_MODE = "devModePref"
  const val ICON_MODE = "iconModePref"
  const val SCREEN_ORIENTATION = "screenOrientationPref"
  const val SHOW_MINI_PLAYER = "showMiniPlayerPref"
  const val GRID_AUTO = "gridViewAutoPref"
  const val MINI_PLAYER_STYLE = "miniPlayerStylePref"
  const val REWIND_BUTTON_STYLE = "rewindButtonStylePref"
  const val PLAY_BUTTON_STYLE = "playButtonStylePref"
  const val SHOW_PROGRESS_BAR = "showProgressBarPref"
  const val SHOW_DIVIDER = "showDividerPref"
  const val USE_ENGLISH = "useEnglishPref"
  const val CURRENT_VOLUME = "CURRENT_VOLUME"
  const val REPEAT_MODE = "REPEAT_MODE"
}
