name: Main

on: [ push, pull_request ]
env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3072m -XX:MaxMetaspaceSize=1g -Xms512m -XX:+HeapDumpOnOutOfMemoryError"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: ./gradlew testDebugUnitTest
      - run: ./gradlew lintKotlin
      - run: ./gradlew app:lintDebug

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: "Artifacts"
          path: |
            artifacts/
            app/build/reports/*.html

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/test-results/**/TEST-*.xml'

  release:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    env:
      ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
      SIGNING_KEYSTORE_PLAY: ${{ secrets.SIGNING_KEYSTORE }}
      SIGNING_PROPERTIES_PLAY: ${{ secrets.SIGNING_PROPERTIES }}
      SIGNING_KEYSTORE_GITHUB: ${{ secrets.SIGNING_KEYSTORE_GITHUB }}
      SIGNING_PROPERTIES_GITHUB: ${{ secrets.SIGNING_PROPERTIES_GITHUB }}
      GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    steps:
      - uses: actions/checkout@v3

      - run: mkdir -p signing/play
      - run: mkdir -p signing/github
      - run: echo $SIGNING_KEYSTORE_PLAY | base64 --decode > signing/play/signing.keystore
      - run: echo $SIGNING_PROPERTIES_PLAY | base64 --decode > signing/play/signing.properties
      - run: echo $SIGNING_KEYSTORE_GITHUB | base64 --decode > signing/github/signing.keystore
      - run: echo $SIGNING_PROPERTIES_GITHUB | base64 --decode > signing/github/signing.properties
      - run: echo $GOOGLE_SERVICES | base64 --decode > app/google-services.json
      - run: ./gradlew app:publishReleaseBundle -PenableCrashlytics -Pvoice.signing.play=true --no-configuration-cache
      - run: ./gradlew app:assembleRelease -PenableCrashlytics -Pvoice.signing.play=false --no-configuration-cache

      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
