name: CI

on: [push]
env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3000m"
jobs:
  build:
    timeout-minutes: 60
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
      
    - name: Fastlane
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: ci

    - uses: actions/upload-artifact@v1.0.0
      if: always()
      with:
        name: "Artifacts"
        path: "artifacts"
